# Generated by Django 3.1.3 on 2020-11-07 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=60)),
                ('currentPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Market', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='StockCollection',
            fields=[
                ('ticker', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('numShares', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='StockEOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EODPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date', models.DateField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbe.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolioID', models.IntegerField(primary_key=True, serialize=False)),
                ('totalValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbe.user')),
            ],
        ),
    ]
